<?php include 'includes/header.php';

$nombreCliente = "   Edward Martinez   ";
$texto = trim($nombreCliente);
$categoria = "Premium";

echo "1. conocer la extencion de un string 'echo strlen(variable)'";
echo "<br>";
echo "<br>";
echo "* ";
echo strlen($nombreCliente);
echo ": muestra solo la extención";
echo "<br>";
echo "* ";
var_dump($nombreCliente);
echo ": muestra el tipo de dato y la extención";
echo "<br>";
echo "<br>";
echo "2. Eliminar los espacios en blanco'";
echo "<br>";
echo "<br>";
echo "* ";
echo strlen($texto);
echo ": elimina los espacios en blanco";
echo "<br>";
echo "<br>";
echo "3. pasar a mayusculas: ";
echo strtoupper($nombreCliente);
echo "<br>";
echo "<br>";
echo "4. pasar a minusculas: ";
echo strtolower($nombreCliente);
echo "<br>";
echo "<br>";
echo "5. Caso de uso:";
echo "<br>";
echo "Esto de mostrar en mayusculas o minusculas lo podemos hacer con CSS sin embargo si necesitamos depronto ver si por ejemplo un usuario esta registrado con un email y tenemos lo siguiente: ";
echo "<br>";
echo "correo@correo.com";
echo "<br>";
echo "Correo@correo.com";
echo "<br>";
echo "es decir, el mismo correo pero uno tiene mayusculas y otro minusculas nos va a generar error, por ello usaremos strtolower para obtener la validación en este caso y True";
echo "<br>";
$mail1 = "correo@correo.com";
$mail2 = "Correo@correo.com";
var_dump(strtolower($mail1) === strtolower($mail2));
echo "<br>";
echo "<br>";
echo "6. Reemplazar texto usando str_replace el resultado es: '";
echo str_replace('Martinez', 'M', $nombreCliente);
echo "' cambio 'Martinez' por la 'M'";
echo "<br>";
echo "<br>";
echo "7. Validación de la existencia de un string: ";
echo strpos($nombreCliente, 'Edward');
echo "<br>";
echo " si el estring no existe PHP no va a imprimir nada";
echo strpos($nombreCliente, 'Pedro');
echo "<br>";
echo "<br>";
echo "8. concatenación";
echo "<br>";
echo "*Opción 1: con punto = ";
echo "El cliente " . $nombreCliente . " es " . $categoria;
echo "<br>";
echo "*Opción 2: con llaves = ";
echo "El cliente {$nombreCliente} es {$categoria}";

include 'includes/footer.php';
